
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') { 
            steps { 
                 sh '''
                        git config --global user.name berchakuwa
                        git config --global user.email berchakuwa@github.com
                        git config -l
                    '''
                 }
        }

        stage('Build') { 
            steps { 
                sh '''
                   cd leumi-project/src/flask
                   usermod -a -G sudo jenkins
                   docker image build -t flask_docker .
                   '''
            }
        }
        stage('Test'){
            steps {
               sh ''' 
                 docker run -p 5000:5000 -d flask_docker
               '''  
           }
        }
        stage('Deploy') {
            steps {
                
                   sh '''
                      echo "push to registry image"
                      docker tag flask_docker 1berchakuwa/flask-docker
                      docker push 1berchakuwa/flask-docker
                   '''
           }
        }
    }
}
