
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') { 
            steps { 
                 sh '''
                    git config --global user.name berchakuwa
                        git config --global user.email berchakuwa@gmail.com
                        git config -l
                    '''
                withCredentials([usernamePassword(credentialsId: 'berchakuwa', passwordVariable: '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', usernameVariable: 'GIT_USERNAME')]) {
                    sh '''
                        git clone https://github.com/Olka0/project-leimi-bank.git
                       '''
                  }
            }
        }

        stage('Build') { 
            steps { 
                echo 'Test'
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy') {
            steps {
                script{
                      echo "push to registry image"
                }
            }
        }
    }
}
