apiVersion : v2
name       : leumi-project
description: A Helm chart for Kubernetes
type       : application
version    : 0.1.0
appVersion : "1.16.0"

maintainers:
    - name : Olga Partin
      email: berchakuwa@gmail.com
      url  : https://github.com/Olka0/project-leimi-bank
